package com.app.printollo.models

data class UserModel (
    val id: String?,
    val userName: String?,
    val firstName: String?,
    val lastName: String?,
    val password: String?,
    val role: String?,
    val email: String?,
    val phoneNumber: String?,
    val lastLoginDate: String?,
    val timeZone: String?,
    val lang: String?,
    val isDeleted: Boolean?,
    val deletedDate: String?,
    val deletedbyUserId: String?,
    //val companies	List<CompanyModel>,
    //abstract var roles	List<E>
    //abstract var deviceRoles	List<E>
    //abstract var claims	List<UserClaimModel>
    val templateId: Int?,
    val accessToClientsView: Boolean?,
    val canAddClients: Boolean?,
    val canEditClients: Boolean?,
    val canDeleteClients: Boolean?,
    val accessToTokensView: Boolean?,
    val canGenerateTokens: Boolean?,
    val accessToAlarmsView: Boolean?,
    val accessToUsersView: Boolean?,
    val canAddUsers: Boolean?,
    val canEditUsers: Boolean?,
    val canDeleteUsers: Boolean?,
    val accessToInstallersView: Boolean?,
    val canAddInstallers: Boolean?,
    val canEditInstallers: Boolean?,
    val canDeleteInstallers: Boolean?,
    val canLockInstallers: Boolean?,
    val accessToDevicesView: Boolean?,
    val canAddDevices: Boolean?,
    val canEditDevices: Boolean?,
    val canDeleteDevices: Boolean?,
    val accessToCalendarView: Boolean?,
    val canAddEvents: Boolean?,
    val canDeleteEvents: Boolean?,
    val rodo: Boolean?,
    val accessNotifications: Boolean?,
    val canAddSIMCard: Boolean?,
    val canImportSIMCards: Boolean?,
    val accessSIMCards: Boolean?,
)